FROM python:3.10.7-alpine
RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /app
ENTRYPOINT ["python"]
CMD ["rest.py"]
